package ast

type Visitor interface {
	VisitModule(m *Module) TreePrinter
	VisitDeclaration(m *Decl) TreePrinter
	VisitImport(m *Import) TreePrinter
	VisitSetting(m *Setting) TreePrinter
	VisitEntryFn(m *EntryFn) TreePrinter
	VisitDeclBase(m *DeclBase) TreePrinter
	VisitInvalidDecl(m *InvalidDecl) TreePrinter
	VisitFunction(m *Function) TreePrinter
	VisitVarDecl(m *VarDecl) TreePrinter
	VisitConstDecl(m *ConstDecl) TreePrinter
	VisitTypeDecl(m *TypeDecl) TreePrinter
	VisitStdFunction(m *StdFunction) TreePrinter
	VisitExprBase(m *ExprBase) TreePrinter
	VisitInvalidExpr(m *InvalidExpr) TreePrinter
	VisitBinaryExpr(m *BinaryExpr) TreePrinter
	VisitUnaryExpr(m *UnaryExpr) TreePrinter
	VisitOfTypeExpr(m *OfTypeExpr) TreePrinter
	VisitLiteralKind(m *LiteralKind) TreePrinter
	VisitLiteralExpr(m *LiteralExpr) TreePrinter
	VisitBoolLiteral(m *BoolLiteral) TreePrinter
	VisitIdentExpr(m *IdentExpr) TreePrinter
	VisitSelectorExpr(m *SelectorExpr) TreePrinter
	VisitCallExpr(m *CallExpr) TreePrinter
	VisitUnfoldExpr(m *UnfoldExpr) TreePrinter
	VisitConversionExpr(m *ConversionExpr) TreePrinter
	VisitTypeExpr(m *TypeExpr) TreePrinter
	VisitNotNilExpr(m *NotNilExpr) TreePrinter
	VisitGeneralBracketExpr(m *GeneralBracketExpr) TreePrinter
	VisitArrayCompositeExpr(m *ArrayCompositeExpr) TreePrinter
	VisitClassCompositeExpr(m *ClassCompositeExpr) TreePrinter
	VisitValuePair(m *ValuePair) TreePrinter
	VisitTypeBase(m *TypeBase) TreePrinter
	VisitPredefinedType(m *PredefinedType) TreePrinter
	VisitInvalidType(m *InvalidType) TreePrinter
	VisitTypeRef(m *TypeRef) TreePrinter
	VisitVectorType(m *VectorType) TreePrinter
	VisitClassType(m *ClassType) TreePrinter
	VisitField(m *Field) TreePrinter
	VisitFuncType(m *FuncType) TreePrinter
	VisitParam(m *Param) TreePrinter
	VisitVariadicType(m *VariadicType) TreePrinter
	VisitMayBeType(m *MayBeType) TreePrinter
	VisitStatementBase(m *StatementBase) TreePrinter
	VisitStatementSeq(m *StatementSeq) TreePrinter
	VisitExprStatement(m *ExprStatement) TreePrinter
	VisitDeclStatement(m *DeclStatement) TreePrinter
	VisitAssignStatement(m *AssignStatement) TreePrinter
	VisitIncStatement(m *IncStatement) TreePrinter
	VisitDecStatement(m *DecStatement) TreePrinter
	VisitIf(m *If) TreePrinter
	VisitGuard(m *Guard) TreePrinter
	VisitSelect(m *Select) TreePrinter
	VisitCase(m *Case) TreePrinter
	VisitSelectType(m *SelectType) TreePrinter
	VisitCaseType(m *CaseType) TreePrinter
	VisitWhile(m *While) TreePrinter
	VisitCycle(m *Cycle) TreePrinter
	VisitCrash(m *Crash) TreePrinter
	VisitReturn(m *Return) TreePrinter
	VisitBreak(m *Break) TreePrinter
	VisitScope(m *Scope) TreePrinter
	VisitModifier(m *Modifier) TreePrinter
}
